name: Backend CD

on:
  push:
    branches: [ main ]
    paths:
    - 'starter/backend/**'
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install pipenv and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        cd starter/backend
        pipenv install --dev

    - name: Build Docker image
      run: |
        cd starter/backend
        docker build --tag 356698323071.dkr.ecr.us-east-1.amazonaws.com/movie-picture-backend:${{ github.sha }} .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 356698323071.dkr.ecr.us-east-1.amazonaws.com

    - name: Push Docker image to ECR
      run: |
        docker push 356698323071.dkr.ecr.us-east-1.amazonaws.com/movie-picture-backend:${{ github.sha }}

    - name: Setup Kustomize and Kubernetes
      uses: imranismail/setup-kustomize@v1

    - name: Deploy to Kubernetes
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name picture-cluster
        cd starter/backend/k8s
        kustomize edit set image backend=356698323071.dkr.ecr.us-east-1.amazonaws.com/movie-picture-backend:${{ github.sha }}
        kustomize build | kubectl apply -f -