name: Backend CD

on:
  push:
    branches: [ main ]
    paths:
    - 'starter/backend/**'
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 356698323071.dkr.ecr.us-east-1.amazonaws.com

    - name: Configure Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image for arm64
      uses: docker/build-push-action@v2
      with:
        context: ./starter/backend
        file: ./starter/backend/Dockerfile
        push: true
        tags: 356698323071.dkr.ecr.us-east-1.amazonaws.com/movie-picture-backend:${{ github.sha }}
        platforms: linux/arm64
      
    - name: Setup Kustomize and Kubernetes
      uses: imranismail/setup-kustomize@v1

    - name: Deploy to Kubernetes
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name picture-cluster
        cd starter/backend/k8s
        kustomize edit set image backend=356698323071.dkr.ecr.us-east-1.amazonaws.com/movie-picture-backend:${{ github.sha }}
        kustomize build | kubectl apply -f -
