name: Backend CI

on:
  pull_request:
    branches: [ main ]
    paths:
    - 'backend/**'
  workflow_dispatch:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install pipenv and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        cd backend
        pipenv install --dev

    - name: Run tests
      run: |
        cd backend
        pipenv run test

    - name: Run linter
      run: |
        cd backend
        pipenv run lint
