name: Backend CD

on:
  push:
    branches: [ main ]
    paths:
    - 'starter/backend/**'
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install pipenv and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        cd starter/backend
        pipenv install --dev

    - name: Linting
      run: cd starter/backend && pipenv run lint

    - name: Run tests
      run: cd starter/backend && pipenv run test

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install pipenv and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        cd starter/backend
        pipenv install --dev

    - name: Build Docker image
      run: |
        cd starter/backend
        docker build --tag 356698323071.dkr.ecr.us-east-1.amazonaws.com/movie-picture-backend:${{ github.sha }} .

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry: '356698323071.dkr.ecr.us-east-1.amazonaws.com'

    - name: Push Docker image to ECR
      run: |
        docker push 356698323071.dkr.ecr.us-east-1.amazonaws.com/movie-picture-backend:${{ github.sha }}

    - name: Setup Kustomize and Kubernetes
      uses: imranismail/setup-kustomize@v1

    - name: Deploy to Kubernetes
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name <EKS_CLUSTER_NAME>
        cd starter/backend/k8s
        kustomize edit set image backend=356698323071.dkr.ecr.us-east-1.amazonaws.com/movie-picture-backend:${{ github.sha }}
        kustomize build | kubectl apply -f -
